import { gql, useMutation, useQuery } from "@apollo/client"
import Head from "next/head"
import Link from "next/link"
import Image from "next/image"

import { useRouter } from "next/router"
import { useLogin } from "resources/auth"

export default function Home() {
  const router = useRouter()

  const variables = {
    identifier: "me+1@shaunpearce.ie",
    password: "Password123!",
  }

  const onComplete = () => {
    router.push("/podcasts")
  }

  const [login] = useLogin({ variables, onComplete })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/podcasts">
          <a>Podcasts</a>
        </Link>
        <button onClick={login}>LOGINNN</button>
      </main>
    </>
  )
}
